export const Constants = {
    URLSERVICE: 'http://192.168.1.5/organizate_api/',
    INCOME: 1,
    EGRESS: 2
};

export const ActionsConstants = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    //SERVICE ACTIONS
    ADD_SERVICE_SUCCESS: 'ADD_SERVICE_SUCCESS',
    ADD_SERVICE_ERROR: 'ADD_SERVICE_ERROR',
    UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
    UPDATE_SERVICE_ERROR: 'UPDATE_SERVICE_ERROR',
    GET_SERVICE_SUCCESS: 'GET_SERVICE_SUCCESS',
    GET_SERVICE_ERROR: 'GET_SERVICE_ERROR',
    GET_ALL_SERVICE_SUCCESS: 'GET_ALL_SERVICE_SUCCESS',
    GET_ALL_SERVICE_ERROR: 'GET_ALL_SERVICE_ERROR',
    DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
    DELETE_SERVICE_ERROR: 'DELETE_SERVICE_ERROR',
    //CUSTOMER ACTIONS
    ADD_CUSTOMER_SUCCESS: 'ADD_CUSTOMER_SUCCESS',
    ADD_CUSTOMER_ERROR: 'ADD_CUSTOMER_ERROR',
    UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
    UPDATE_CUSTOMER_ERROR: 'UPDATE_CUSTOMER_ERROR',
    GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
    GET_CUSTOMER_ERROR: 'GET_CUSTOMER_ERROR',
    GET_ALL_CUSTOMER_SUCCESS: 'GET_ALL_CUSTOMER_SUCCESS',
    GET_ALL_CUSTOMER_ERROR: 'GET_ALL_CUSTOMER_ERROR',
    DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
    DELETE_CUSTOMER_ERROR: 'DELETE_CUSTOMER_ERROR',
    //INCOME EGRESS ACTION
    ADD_INCOME_EGRESS_SUCCESS: 'ADD_INCOME_EGRESS_SUCCESS',
    ADD_INCOME_EGRESS_ERROR: 'ADD_INCOME_EGRESS_ERROR',
    UPDATE_INCOME_EGRESS_SUCCESS: 'UPDATE_INCOME_EGRESS_SUCCESS',
    UPDATE_INCOME_EGRESS_ERROR: 'UPDATE_INCOME_EGRESS_ERROR',
    GET_INCOME_EGRESS_SUCCESS: 'GET_INCOME_EGRESS_SUCCESS',
    GET_INCOME_EGRESS_ERROR: 'GET_INCOME_EGRESS_ERROR',
    GET_ALL_INCOME_EGRESS_SUCCESS: 'GET_ALL_INCOME_EGRESS_SUCCESS',
    GET_ALL_INCOME_EGRESS_ERROR: 'GET_ALL_INCOME_EGRESS_ERROR',
    DELETE_INCOME_EGRESS_SUCCESS: 'DELETE_INCOME_EGRESS_SUCCESS',
    DELETE_INCOME_EGRESS_ERROR: 'DELETE_INCOME_EGRESS_ERROR',
    //HOME SCHEDULE
    GET_SCHEDULE_SUCCESS: 'GET_SCHEDULE_SUCCESS',
    GET_SCHEDULE_ERROR: 'GET_SCHEDULE_ERROR'
}

export const Days = [
    'Dom.',
    'Lun.',
    'Mar.',
    'Mie.',
    'Jue.',
    'Vie.',
    'Sab.'
]