export const Constants = {
    URLSERVICE: 'http://localhost/organizate_api/'
};

export const ActionsConstants = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    ADD_SERVICE_SUCCESS: 'ADD_SERVICE_SUCCESS',
    ADD_SERVICE_ERROR: 'ADD_SERVICE_ERROR',
    UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
    UPDATE_SERVICE_ERROR: 'UPDATE_SERVICE_ERROR',
    GET_SERVICE_SUCCESS: 'GET_SERVICE_SUCCESS',
    GET_SERVICE_ERROR: 'GET_SERVICE_ERROR',
    GET_ALL_SERVICE_SUCCESS: 'GET_ALL_SERVICE_SUCCESS',
    GET_ALL_SERVICE_ERROR: 'GET_ALL_SERVICE_ERROR'
}