const URLPRODUCCION = 'http://staging.sayasoftware.com/organizate_api/';
const URLTESTING = 'http://192.168.1.7/organizate_api/';

export const Constants = {
    URLSERVICE: URLPRODUCCION,
    INCOME: 1,
    EGRESS: 2
};

export const ActionsConstants = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    //SERVICE ACTIONS
    ACTIONS_SERVICE_LOADING: 'ACTIONS_SERVICE_LOADING',
    ADD_SERVICE_SUCCESS: 'ADD_SERVICE_SUCCESS',
    ADD_SERVICE_ERROR: 'ADD_SERVICE_ERROR',
    UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
    UPDATE_SERVICE_ERROR: 'UPDATE_SERVICE_ERROR',
    DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
    DELETE_SERVICE_ERROR: 'DELETE_SERVICE_ERROR',
    GET_SERVICE_LOADING: 'GET_SERVICE_LOADING',
    GET_ALL_SERVICE_SUCCESS: 'GET_ALL_SERVICE_SUCCESS',
    GET_ALL_SERVICE_ERROR: 'GET_ALL_SERVICE_ERROR',
    //CUSTOMER ACTIONS
    ACTIONS_CUSTOMER_LOADING: 'ACTIONS_CUSTOMER_LOADING',
    ADD_CUSTOMER_SUCCESS: 'ADD_CUSTOMER_SUCCESS',
    ADD_CUSTOMER_ERROR: 'ADD_CUSTOMER_ERROR',
    UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
    UPDATE_CUSTOMER_ERROR: 'UPDATE_CUSTOMER_ERROR',
    DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
    DELETE_CUSTOMER_ERROR: 'DELETE_CUSTOMER_ERROR',
    GET_CUSTOMERS_LOADING: 'GET_CUSTOMERS_LOADING',
    GET_ALL_CUSTOMER_SUCCESS: 'GET_ALL_CUSTOMER_SUCCESS',
    GET_ALL_CUSTOMER_ERROR: 'GET_ALL_CUSTOMER_ERROR',
    //INCOME EGRESS ACTION
    ACTIONS_INCOME_EGRESS_LOADING: 'ACTIONS_INCOME_EGRESS_LOADING',
    ADD_INCOME_EGRESS_SUCCESS: 'ADD_INCOME_EGRESS_SUCCESS',
    ADD_INCOME_EGRESS_ERROR: 'ADD_INCOME_EGRESS_ERROR',
    UPDATE_INCOME_EGRESS_SUCCESS: 'UPDATE_INCOME_EGRESS_SUCCESS',
    UPDATE_INCOME_EGRESS_ERROR: 'UPDATE_INCOME_EGRESS_ERROR',
    DELETE_INCOME_EGRESS_SUCCESS: 'DELETE_INCOME_EGRESS_SUCCESS',
    DELETE_INCOME_EGRESS_ERROR: 'DELETE_INCOME_EGRESS_ERROR',
    GET_INCOME_EGRESS_LOADING: 'GET_INCOME_EGRESS_LOADING',
    GET_ALL_INCOME_EGRESS_SUCCESS: 'GET_ALL_INCOME_EGRESS_SUCCESS',
    GET_ALL_INCOME_EGRESS_ERROR: 'GET_ALL_INCOME_EGRESS_ERROR',
    GET_ALL_RESET_STATE: 'GET_ALL_RESET_STATE',
    //HOME SCHEDULE
    GET_SCHEDULE_SUCCESS: 'GET_SCHEDULE_SUCCESS',
    GET_SCHEDULE_ERROR: 'GET_SCHEDULE_ERROR'
}

export const Days = [
    'Dom.',
    'Lun.',
    'Mar.',
    'Mie.',
    'Jue.',
    'Vie.',
    'Sab.'
]